packages:
  - '.'
autoInstallPeers: false

allowBuilds:
  electron: true
  electron-winstaller: true

linkWorkspacePackages: true
preferWorkspacePackages: true
minimumReleaseAgeExclude:
  - '@sparkelf/dsh-plugin-supervisor@0.1.4'
